- src/components/App/App.js
- src/components/Template/Template.js
- src/components/Template/Template.style.js
> built simple template component directory

- package.json
- yarn.lock
> set up file structure for redux implementation

- src/components/Template/Template.js
- src/components/Template/Template.style.js
> updated template file and fixed error for View tag

- package.json
- src/components/App/App.js
- src/components/TempBeerList/TempBeerList.js
- src/state/actions.js
- src/state/reducers/globalReducer.js
- src/state/reducers/listsReducer.js
- src/state/store.js
- yarn.lock
create store
create global reducer and lists reducer
create first redux action
create temporary component to 'connect' to the redux store
closes #5
> implement redux in app

- src/components/App/App.js
- src/components/App/App.style.js
- src/components/List/List.js
- src/components/List/List.style.js
- src/components/Template/Template.js
> rendered out a scrollable List component

- src/components/App/App.js
- src/components/App/App.style.js
- src/components/Lists/Lists.js
- src/utils/style.js
> add util style object for easy reusability for common styles

- src/components/List/List.js
- src/components/List/List.style.js
- src/state/actions.js
- src/state/reducers/listsReducer.js
> implemented renaming of list functionality

- src/components/List/List.js
- src/components/Table/Table.js
- src/state/reducers/listsReducer.js
- src/utils/generateList.js
create Table component and implement basic display of table
closes #47
> expand data structure of list rows, columns, and data

- src/components/List/List.js
- src/components/List/List.style.js
- src/components/Table/Table.js
> remove unused imports and styles

- src/components/CreateList/CreateList.js
- src/components/List/List.js
- src/components/Table/Table.js
- src/state/actions.js
- src/state/reducers/listsReducer.js
- src/utils/generateExampleList.js
- src/utils/style.js
add basic table styles to structure it somewhat properly
> add button to create example list

- src/components/List/List.js
- src/state/actions.js
- src/state/reducers/listsReducer.js
- src/utils/generateColumn.js
> implemented add column ui and generated column functionality

- scripts/templates/Component.js
> refactored template script

- src/components/Table/Table.js
- src/state/reducers/listsReducer.js
- src/utils/table.js
> create cells when adding rows and columns

- README.md
> add README docs for conditional rendering in the JS Style Guide

- src/components/Table/Cell.js
- src/components/Table/Table.js
- src/components/Table/Table.style.js
- src/state/actions.js
- src/state/reducers/listsReducer.js
- src/utils/generateColumn.js
- src/utils/generateExampleList.js
- src/utils/generateList.js
- src/utils/generateRow.js
In the current state, any cell can be edited but only data cells (i.e. the inner cells, not the headers) will update when the OK button is pressed
closes #73
> add ability to edit cell value

- src/components/Table/Cell.js
> improve update-cell UI

- src/components/App/App.js
- src/components/App/App.style.js
- src/components/Nav/Nav.js
- src/components/Nav/Nav.style.js
- src/state/actions.js
- src/state/reducers/globalReducer.js
- src/state/reducers/globalUiReducer.js
- src/utils/style.js
the nav comes out like a shelf from the left side of the screen
nav is currently unstyled
closes #84
> add nav component

- src/components/Buttons/NavButton/NavButton.js
- src/components/Buttons/NavButton/NavButton.style.js
> Created an arrow button component to be used as the nav toggle button

- scripts/templates/Component.js
replaced placeholder text to render out new Component name
closes #91
> updated template componented to be a React Pure component

- src/components/App/App.js
- src/components/App/App.style.js
- src/components/Buttons/NavButton/NavButton.js
- src/components/Buttons/NavButton/NavButton.style.js
> replace placeholder nav button with NavButton component

- src/components/App/App.js
- src/components/App/App.style.js
- src/components/Lists/Lists.js
- src/components/Lists/Lists.style.js
- src/components/Nav/Nav.js
- src/components/Nav/Nav.style.js
- src/state/reducers/globalUiReducer.js
> move Create List input into Nav

- src/components/Nav/Nav.js
- src/utils/generateExampleList.js
- src/utils/generateList.js
add a 'name' field to the list data model
closes #103
> display list names in the nav

- src/components/App/App.js
When a new list is created, set it as the active list
When a list is deleted, do not have any list set as the active list
> improve setting the active list automatically

- src/components/CreateList/CreateList.js
- src/components/Nav/Nav.style.js
orange, black, and yellow for halloween ooOooOOoOo
> nav: change colors for the month of October

- .gitignore
- README.md
- app.json
- package.json
- yarn.lock
> upgraded current project to run with the Expo SDK

- android/app/build.gradle
- android/app/src/main/java/com/botghaninotepad/MainActivity.java
- android/app/src/main/java/com/botghaninotepad/MainApplication.java
- android/settings.gradle
- ios/botghaniNotepad.xcodeproj/project.pbxproj
- ios/botghaniNotepad/AppDelegate.m
- package.json
- yarn.lock
update ios and android files to configure react-native-navigation
https://wix.github.io/react-native-navigation/#/installation-ios
https://wix.github.io/react-native-navigation/#/installation-android
foundation for #129
> install react-native-navigation

- android/app/build.gradle
- android/app/src/main/java/com/botghaninotepad/MainActivity.java
- android/app/src/main/java/com/botghaninotepad/MainApplication.java
- android/settings.gradle
- ios/botghaniNotepad.xcodeproj/project.pbxproj
- ios/botghaniNotepad/AppDelegate.m
- package.json
- yarn.lock
This reverts commit d11198f8c1e41c693a827e9ae5ef6bb8852cfe5a.
> Revert "install react-native-navigation"

- src/components/App/App.js
- src/components/Buttons/NavButton/NavButton.js
- src/components/ListHeader/ListHeader.js
connected both NavButton + ListHeader component to redux
inside of the App's new top navigation bar the headerLeft component is NavButton and the headerTitle component is now ListHeader
closes #96
> septerated the Nav Button from the ListHeader component

- scripts/component.js
- src/components/App/App.js
- src/components/Buttons/NavButton/NavButton.js
- src/components/Buttons/NavButton/NavButton.style.js
- src/components/Nav/Nav.js
- src/components/Table/Cell.js
- src/state/actions.js
- src/state/reducers/globalUiReducer.js
> Cleanup from Drawer Implementation

- src/components/Table/Cell.js
- src/state/actions.js
- src/state/reducers/listsReducer.js
- src/utils/generateExampleList.js
- src/utils/generateList.js
> Set createdAt and updatedAt date stamps to List data

- src/components/App/App.js
- src/components/ButtonMenu/ButtonMenu.js
- src/components/Modal/Modal.js
- src/components/Modal/Modal.style.js
- src/components/Nav/Nav.js
- src/state/actions.js
- src/state/reducers/globalUiReducer.js
- src/styles/colors.js
> Delete list confirmation modal

- BotghaniNotepad.js
- scripts/templates/Component.js
- src/components/ButtonMenu/ButtonMenu.js
- src/components/ButtonMenu/ButtonMenu.style.js
- src/components/CreateList/CreateList.js
- src/components/CreateList/CreateList.style.js
- src/components/Modal/Modal.js
- src/components/Nav/Nav.js
- src/components/Nav/Nav.style.js
- src/components/Splash/Splash.js
- src/components/Splash/Splash.style.js
- src/styles/colors.js
add space above the app header for phone native info bar (with time, battery, etc.)
improve styles for exampleList button and deleteList button
foundation for #138
> implement a basic splash screen

- BotghaniNotepad.js
- package.json
- src/state/store.js
- yarn.lock
> Integrated redux-persist for persisting storage

- src/components/App/App.js
> Open navigation drawer upon deletion of current list

- src/components/App/App.js
- src/components/ButtonMenu/ButtonMenu.js
- src/state/actions.js
- src/state/reducers/globalUiReducer.js
upon rendering of the app if a favourite list is persisted in the state it is also the activeList
closes #151
> users can now favourite/unfavourite one list

- src/components/Nav/Nav.js
- src/components/Nav/Nav.style.js
> lists inside the nav now display if they are favourited or not

- BotghaniNotepad.js
- src/components/CreateList/CreateList.js
- src/components/CreateList/CreateList.style.js
- src/components/Nav/Nav.js
- src/components/Nav/Nav.style.js
- src/styles/colors.js
designs are partially from #142
> improve header and nav styles

- src/components/App/App.js
- src/components/App/__tests__/App.test.js
- src/components/App/__tests__/__snapshots__/App.test.js.snap
- src/components/List/List.js
> added tests for app

- BotghaniNotepad.js
> Dismiss keyboard upon opening + closing the nav

- src/components/List/Cell.jsx
- src/components/List/List.style.js
> added guard in Cell component did update to properly update state value

- src/components/Splash/Splash.jsx
- src/components/Splash/Splash.style.js
> animation added to paper svg on splash screen

- src/components/ButtonMenu/ButtonMenu.style.js
closes #205
Before:
---
After:
> set maxWidth on ListHeader title to prevent layout weirdness

- src/state/newActions.js
- src/state/reducers/newListReducer.js
- src/state/reducers/tests/newListReducer.test.js
This reducer reflects the new list state and will eventually replace the
existing list reducer.
closes #223
> create new list reducer

- src/utils/list.js
- src/utils/tests/list.test.js
This contains methods to create lists, items, and notes, as well as
PropType definitions for each.
> add new list helpers
